# Generated by Django 4.0.5 on 2022-11-26 12:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(blank=True, default='', max_length=50, validators=[django.core.validators.MaxLengthValidator(50)], verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default='', max_length=50, validators=[django.core.validators.MaxLengthValidator(50)], verbose_name='Last Name')),
                ('isBanned', models.BooleanField(default=False, verbose_name='Is Banned?')),
                ('isVerified', models.BooleanField(default=False, verbose_name='Is Verified ?')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Seller', 'Seller'), ('Customer', 'Customer'), ('Viewer', 'Viewer')], default='Customer', max_length=50, verbose_name='Role')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('addressLine1', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('addressLine2', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('city', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('pincode', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('country', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
