# Generated by Django 4.0.5 on 2022-11-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Seller', 'Seller'), ('Customer', 'Customer'), ('Viewer', 'Viewer')], default='Customer', max_length=50, null=True, verbose_name='Role'),
        ),
    ]
