# Generated by Django 4.0.5 on 2022-11-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type_of_pet', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Hamster', 'Hamster'), ('Other', 'Other')], default='Dog', max_length=50, verbose_name='Type of Pet')),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
