# Generated by Django 4.0.5 on 2022-11-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='current_owner_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Current Owner Name'),
        ),
    ]
