# Generated by Django 4.0.5 on 2022-11-26 09:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('pets', '0002_pet_current_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20, verbose_name='Gender of the Pet'),
        ),
        migrations.AddField(
            model_name='pet',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Maximum image size is 8MB', null=True, upload_to='pet_profiles'),
        ),
        migrations.AddField(
            model_name='pet',
            name='request_sent',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 26, 9, 57, 49, 775016, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='current_owner_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
