# Generated by Django 4.0.5 on 2022-11-26 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('pets', '0002_alter_pet_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='current_owner_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20, null=True, verbose_name='Gender of the Pet'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type_of_pet',
            field=models.CharField(blank=True, choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Hamster', 'Hamster'), ('Other', 'Other')], default='Dog', max_length=50, null=True, verbose_name='Type of Pet'),
        ),
    ]
