# Generated by Django 4.0.5 on 2022-11-26 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('pets', '0003_alter_pet_current_owner_name_alter_pet_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='current_owner_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
